# This is a basic workflow to help you get started with Actions

name: Self Test

# Controls when the action will run. 
on:
  pull_request:
    branches: [ main ]
    types: [closed, opened, synchronize, reopened]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Test
        uses: bengreenier-actions/hacknplan-pr@v1.0.0
        with:
          ghToken: ${{ secrets.GITHUB_TOKEN }}
          apiKey: ${{ secrets.HAP_API_KEY }}
          projectId: 14921
